Update the security-secrets-checker script
edgexfoundry/docker-edgex-consul pull request #10
Opened 2019-11-19 17:03 UTC by jim-wang-intel

Use the new path /tmp/edgex/secrets/* for checking the sentinel files due to the change of splitting vault images

Signed-off-by: Jim Wang <yutsung.jim.wang@intel.com>

2019-11-19 17:09 UTC, jim-wang-intel commented
@lranjbar, @tingyuz   please label this as Geneva and security-services related if you can

2019-11-20 16:32 UTC, jim-wang-intel commented
reviewers: @bnevis-i, @lranjbar, @michaelestrin, @tsconn23

2019-11-20 16:44 UTC, bnevis-i commented
LGTM, but this is blocked on https://github.com/edgexfoundry/docker-edgex-consul/pull/9

2019-11-20 17:03 UTC, bnevis-i requested changes
This is a breaking change for geneva.  VERSION needs to be updated to 1.1.1

2019-11-20 18:30 UTC, jim-wang-intel commented
> 
> 
> This is a breaking change for geneva. VERSION needs to be updated to 1.1.1

From now on, I think we are tracking on the master as we developing. Version is set when the release is ready.

2019-11-20 18:35 UTC, lranjbar commented
We are trying to decouple the version from the branch to make it easier for testing.

2019-11-20 20:13 UTC, michaelestrin commented
> From now on, I think we are tracking on the master as we developing. Version is set when the release is ready.

Does that mean VERSION should be deleted in this PR?

2019-11-20 20:20 UTC, jim-wang-intel commented
> 
> 
> > From now on, I think we are tracking on the master as we developing. Version is set when the release is ready.
> 
> Does that mean VERSION should be deleted in this PR?

No.  I think the "VERSION" file still needs for release on CI pipeline when it is ready.  The majority of time it should be "master" while developing and use it for nightly builds.  I saw @lranjbar Lisa has PR #11  to change it to "master" on this master branch.  @lranjbar please chime in if I am incorrect.

2019-11-20 20:55 UTC, lranjbar commented
> > From now on, I think we are tracking on the master as we developing. Version is set when the release is ready.
> 
> Does that mean VERSION should be deleted in this PR?

It is safe to delete the VERSION file in this repository at this time.

2019-11-21 01:29 UTC, bnevis-i commented
I'm still not tracking this conversation.  In Fuji branch, version is 1.1.0.  Most of the other repos have VERSION == master (after Lisa changed it from 1.1.1).   I am concerned that the nightly scripts will overwrite the fuji branch version of consul with the master branch consul the next time it builds and break fuji if we don't change VERSION.  If you tell me this won't happen I am ok with that.

2019-11-21 01:49 UTC, bnevis-i reviewed
Deleted previous comment.  Looked at PR#11 and convinced myself that the VERSION file is inconsequential now.   Expect approval tomorrow after checking one more thing.

2019-11-21 02:18 UTC, bnevis-i approved these changes

2019-11-22 14:27 UTC, lranjbar approved these changes

2019-11-22 15:01 UTC, merged