Add Jenkinsfile for build automation of docker image
edgexfoundry/docker-edgex-consul pull request #4
Opened 2019-10-21 22:32 UTC by jamesrgregg

- Add Jenkinsfile
- Pushes images to Nexus
- Kicks off Clair scan of the images

Signed-off-by: James Gregg <james.r.gregg@intel.com>

2019-10-21 22:33 UTC, jamesrgregg commented
@ernestojeda @lranjbar please review

2019-10-22 01:06 UTC, ernestojeda approved these changes
Version needs updating

2019-10-22 01:06 UTC, ernestojeda commented on Jenkinsfile
> +                edgeXClair("${env.DOCKER_REGISTRY}:10004/docker-edgex-consul-arm64:1.0.0")
Wrong tag, should be `1.1.0`

2019-10-22 01:07 UTC, ernestojeda requested changes
See my comment about the Clair stage

2019-10-22 01:09 UTC, jamesrgregg commented on Jenkinsfile
> +                edgeXClair("${env.DOCKER_REGISTRY}:10004/docker-edgex-consul-arm64:1.0.0")
oh snap!!

2019-10-22 01:32 UTC, ernestojeda approved these changes
LGTM 👍

2019-10-22 02:27 UTC, merged